---
- name: Cofigure all nodes
  hosts: nodes
  become: true
  roles:
    - create_mapr_user
    - generate_ssh_key
    - ssh_copy_id
    - copy_hosts
    
- name: Download MapR setup script
  hosts: edge
  become: true
  roles:
    - download_mapr_setup