---
- name: Copy SSH public key to all nodes
  become: yes
  become_user: "{{ mapr_user }}"
  authorized_key:
    user: "{{ mapr_user }}"
    key: "{{ lookup('file', '/home/{{ mapr_user }}.ssh/id_rsa.pub') }}"

