---
# edge/controller env variables
hpe_user:  "{{ lookup('env', 'HPE_USER') }}"
hpe_token:  "{{ lookup('env', 'HPE_TOKEN') }}"
mapr_release: "{{ lookup('env', 'MAPR_RELEASE') }}"
mapr_mep_release: "{{ lookup('env', 'MAPR_MEP_RELEASE') }}"

# MapR GPG key URL
mapr_gpg_key_url: "https://{{ hpe_user | urlencode }}:{{ hpe_token }}@package.ezmeral.hpe.com/releases/pub/maprgpg.key"

# MapR repository URLs
mapr_repos:
  - repo: "deb [arch=amd64] https://package.ezmeral.hpe.com/releases/v{{ mapr_release }}/ubuntu/ binary trusty"
  - repo: "deb [arch=amd64] https://package.ezmeral.hpe.com/releases/MEP/MEP-{{ mapr_mep_release }}/ubuntu/ binary trusty"

# Oozie configure
oozie_version: "5.2.0"
oozie_bin_dir: "/opt/mapr/oozie/oozie-{{ oozie_version }}/bin"
oozie_configure_cmd: "{{ oozie_bin_dir }}/configure.sh -R -c --secure"
oozie_url: "https://{{ oozie_node }}:11443/oozie"
oozie_node: "node03.manul.arpa"
    
# MapR nfs mount point
mapr_nfs_directory: "/mapr_nfs"
mapr_nfs_host: "node01"
