---
- name: Execute MapR configure.sh command
  shell: >
    /opt/mapr/server/configure.sh
    -N {{ cluster_name }}
    -c
    -secure
    -C "{{ groups['nodes'] | map('regex_replace', '^(.*)$', '\1.' + cluster_name) | join(',') }}"
    -HS node03.manul.arpa
  register: command_output

- name: Debug command output
  debug:
    var: command_output.stdout_lines
