---
- name: Execute MapR configure.sh command
  shell: >
    /opt/mapr/server/configure.sh
    -N {{ cluster_name }}
    -C "{{ groups['nodes'] | join("." + cluster_name + ",") }}"
    -Z "{{ groups['nodes'] | join("." + cluster_name + ",") }}"
    -c
  register: command_output

- name: Debug command output
  debug:
    var: command_output.stdout_lines
