---
- name: Add MapR repository GPG key
  command: "wget -q -O - --timeout=30 {{ mapr_gpg_key_url }} | apt-key add -"
  become: true

- name: Add MapR repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  become: true
  loop: "{{ mapr_repos }}"
